desc "Updating teams for season 2 (while there is no admin menu)"
task :update_teams => :environment do
  puts "Veterans"

  def self.slug(name)
    I18n.transliterate(name).downcase.gsub(". ", "-").gsub(".","-").gsub(" ","-")
  end

  Api::V1::Team.create(player_id: 4, name: 'PerdiCartola F.C', slug: slug('PerdiCartola F.C'), season_id: 2)
  Api::V1::Team.create(player_id: 3, name: 'Valério Central F. C', slug: slug('Valério Central F. C'), season_id: 2)
  Api::V1::Team.create(player_id: 12, name: 'Batista S.C', slug: slug('Batista S.C'), season_id: 2)
  Api::V1::Team.create(player_id: 10, name: 'C.Luiz', slug: slug('C.Luiz'), season_id: 2)
  Api::V1::Team.create(player_id: 6, name: '47 DO SEGUNDO TEMPO FC', slug: slug('47 DO SEGUNDO TEMPO FC'), season_id: 2)
  Api::V1::Team.create(player_id: 15, name: 'PIEDADE FCF', slug: slug('PIEDADE FCF'), season_id: 2)
  Api::V1::Team.create(player_id: 23, name: 'Raimundões FC', slug: slug('Raimundões FC'), season_id: 2)
  Api::V1::Team.create(player_id: 26, name: 'Emival SCCP', slug: slug('Emival SCCP'), season_id: 2)
  Api::V1::Team.create(player_id: 5, name: 'FaBayern FC', slug: slug('FaBayern FC'), season_id: 2)
  Api::V1::Team.create(player_id: 7, name: 'IslandOfCatsFootball', slug: slug('IslandOfCatsFootball'), season_id: 2)
  Api::V1::Team.create(player_id: 31, name: 'JORGEJOH', slug: slug('JORGEJOH'), season_id: 2)
  Api::V1::Team.create(player_id: 2, name: 'Boa Viagem E. Clube', slug: slug('Boa Viagem E. Clube'), season_id: 2)
  Api::V1::Team.create(player_id: 9, name: 'vovo S.C', slug: slug('vovo S.C'), season_id: 2)
  Api::V1::Team.create(player_id: 1, name: 'Camisa10daGavea', slug: slug('Camisa10daGavea'), season_id: 2)
  Api::V1::Team.create(player_id: 20, name: 'Palestra Cangaceiro', slug: slug('Palestra Cangaceiro'), season_id: 2)
  Api::V1::Team.create(player_id: 24, name: 'Vovô do Yan', slug: slug('Vovô do Yan'), season_id: 2)
  Api::V1::Team.create(player_id: 14, name: 'Down Futball United', slug: slug('Down Futball United'), season_id: 2)
  Api::V1::Team.create(player_id: 27, name: 'Come mosca fc', slug: slug('Come mosca fc'), season_id: 2)
  Api::V1::Team.create(player_id: 13, name: 'Ferrimbahçe', slug: slug('Ferrimbahce'), season_id: 2)
  Api::V1::Team.create(player_id: 8, name: 'Chico e Gunha FC', slug: slug('Chico e Gunha FC'), season_id: 2)
  Api::V1::Team.create(player_id: 11, name: 'Phode Chorarr FC', slug: slug('Phode Chorarr FC'), season_id: 2)
  Api::V1::Team.create(player_id: 21, name: 'FC Cara Seca', slug: slug('FC Cara Seca'), season_id: 2)
  Api::V1::Team.create(player_id: 17, name: 'Vanduka FC', slug: slug('Vanduka FC'), season_id: 2)
  Api::V1::Team.create(player_id: 16, name: 'Victor Gomes Sporting Club', slug: slug('Victor Gomes Sporting Club'), season_id: 2)
  Api::V1::Team.create(player_id: 18, name: 'VBSantiago FC', slug: slug('VBSantiago FC'), season_id: 2)
  Api::V1::Team.create(player_id: 29, name: 'Cachagol FC', slug: 'cachagol-fc', season_id: 2)
  Api::V1::Team.create(player_id: 30, name: 'simple man', slug: 'simple-man', season_id: 2)
  Api::V1::Team.create(player_id: 33, name: 'djmss fc', slug: 'djmss-fc', season_id: 2)
  puts "New players"
  player = Api::V1::Player.create(name: 'Bruno Pinheiro', active: true)
  Api::V1::Team.create(name: 'Rua02 FA', slug: slug('Rua02 FA'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Carlos Eduardo', active: true)
  Api::V1::Team.create(name: 'SergioMoro18', slug: slug('SergioMoro18'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Daniel Zanata', active: true)
  Api::V1::Team.create(name: 'Zanatinha CFC', slug: slug('Zanatinha CFC'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Felipe Parteira', active: true)
  Api::V1::Team.create(name: 'Cearamor Messejana', slug: slug('Cearamor Messejana'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Diogo', active: true)
  Api::V1::Team.create(name: 'Cearamengofc', slug: slug('Cearamengofc'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Elano Matos', active: true)
  Api::V1::Team.create(name: 'Pau Serrado FC', slug: slug('Pau Serrado FC'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Ivolnildo', active: true)
  Api::V1::Team.create(name: 'coringao team1', slug: slug('coringao team1'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Karlos Emanuel', active: true)
  Api::V1::Team.create(name: 'Clube Artimanhã', slug: slug('Clube Artimanhã'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Lucas Emanuel', active: true)
  Api::V1::Team.create(name: 'galaticobola', slug: slug('galaticobola'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Marcelo Pascoal', active: true)
  Api::V1::Team.create(name: 'Celim Team', slug: slug('Celim Team'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Márcio Fernandes', active: true)
  Api::V1::Team.create(name: 'Gigante Alvinegro FC', slug: slug('Gigante Alvinegro FC'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Messias Cezar', active: true)
  Api::V1::Team.create(name: 'Mumbaba Futebol Clube', slug: slug('Mumbaba Futebol Clube'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Victor Bessa', active: true)
  Api::V1::Team.create(name: 'Bessa CSC', slug: slug('Bessa CSC'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Yuri Silva', active: true)
  Api::V1::Team.create(name: 'FutArte FEC', slug: slug('FutArte FEC'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Willame', active: true)
  Api::V1::Team.create(name: 'FlaMegue FC', slug: slug('FlaMegue FC'), player_id: player.id, season_id: 2)
  player = Api::V1::Player.create(name: 'Paulo Cristiano', active: true)
  Api::V1::Team.create(name: 'Ragnar Lothbrok 2018', slug: slug('Ragnar Lothbrok 2018'), player_id: player.id, season_id: 2)
  puts "done."
end
