---
openapi: 3.0.1
info:
  title: API V1
  version: v1
definitions:
  score:
    round:
      type: integer
    points:
      type: number
      multipleOf: 0.1
  player:
    type: object
    properties:
      name:
        type: string
      team:
        type: string
      team_symbol:
        type: string
      points:
        type: number
        multipleOf: 0.1
      details:
        type: array
        items:
          type: object
          properties:
            round:
              type: integer
            points:
              type: number
              multipleOf: 0.1
paths:
  "/api/v1/dispute_months":
    get:
      summary: dispute_months
      tags:
      - Scores/DisputeMonth
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/DisputeMonth"
components:
  schemas:
    DisputeMonth:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        players:
          type: array
          items:
            "$ref": "#/definitions/player"
servers:
- url: https://localhost:3001
  variables:
    defaultHost:
      default: http://localhost:3001
